Fix fail to resume PDF
After 72b4af8 ("Port to Python 3") the activity fails to resume PDF
files.

Traceback (most recent call last):
  File "/home/guest/Activities/Read.activity/readactivity.py", line 99, in get_md5
    buf = fh.read(4096)
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte

Cause is opening the file as text, yet the file is not text.

Fix is to open as binary.

Thanks to Swarup for identifying an alternative solution that generated
incorrect md5sums.

Fixes https://github.com/sugarlabs/read-activity/issues/36