EPub: make the ET recognize HTML entities
Native HTML support in ElementTree never really worked and is marked
deprecated in Python 3. This means it blows up upon encountering an
entity that is not a XML entity. Sigh.

  Exception in thread Thread-1:
  Traceback (most recent call last):
    File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
      self.run()
    File "/home/lkundrak/epub/read-activity/epubview/jobs.py", line 90, in run
      self._start_search()
    File "/home/lkundrak/epub/read-activity/epubview/jobs.py", line 55, in _start_search
      if self._searchfile(f):
    File "/home/lkundrak/epub/read-activity/epubview/jobs.py", line 71, in _searchfile
      tree = etree.parse(fileobj, parser=parser)
    File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
      tree.parse(source, parser)
    File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 656, in parse
      parser.feed(data)
    File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1659, in feed
      self._raiseerror(v)
    File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
      raise err
  ParseError: undefined entity &nbsp;: line 35, column 132

Fixes: a55a0cc6d70215ccb0d887df81555ef9edb09732